### ISSUE TITLE
Adding labels to swipeable view

### ISSUE THREAD

**Issue by ConnectQ** [muhammadbassio/MABCardsView#1]
I added a label to the swipeable view, however, it doesn't move with the card. E.g. If I swipe left or right the label stays in the set position within the view.

I'm not entirely sure what I did wrong. I tried adding sub-view within the swipeable view and then adding the label to that view but I didn't have any luck.

Additionally, is it possible to make an array of the 'cards'?

**Comment by muhammadbassio** [comment]
Hi,
You need to add the label to the card view, you can do that either by subclassing "MABCardView" or by adding the label to the card view in the dataSource method "nextCardViewForContainerView", if the problem still exists, please share your code.

Regarding the second point, I am not sure why you need to create an array of cards, they already work as UITableView & UICollectionView, please explain what you mean in more details.

**Comment by ConnectQ** [comment]
Thanks for the reply, I managed to get that working with your help.

Basically I want the user to add their name via a text field on the card but for the text to be still there when you reload the cards?

**Comment by muhammadbassio** [comment]
then you should store the text strings in an array & retrieve the desired value depending on the index when loading card using the dataSource method "nextCardViewForContainerView"
